!STARTOFREGISTRYGENERATEDFILE 'AeroDyn_Inflow_C_Binding_Types.f90'
!
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
!
! FAST Registry
!*********************************************************************************************************************************
! AeroDyn_Inflow_C_Binding_Types
!.................................................................................................................................
! This file is part of AeroDyn_Inflow_C_Binding.
!
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
!
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!
!     http://www.apache.org/licenses/LICENSE-2.0
!
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
!
!
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in AeroDyn_Inflow_C_Binding. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.
MODULE AeroDyn_Inflow_C_Binding_Types
!---------------------------------------------------------------------------------------------------------------------------------
USE NWTC_Library
IMPLICIT NONE
    INTEGER(IntKi), PUBLIC, PARAMETER  :: NumPtsDiskAvg = 144      ! Number of points for disk average velocity calculations [-]
! =========  DiskAvgVelData  =======
  TYPE, PUBLIC :: DiskAvgVelData
    REAL(ReKi) , DIMENSION(1:3,1:NumPtsDiskAvg)  :: DiskWindPosRel = 0.0_ReKi      !< Position points for disk average sampling, relative to hub [-]
    REAL(ReKi) , DIMENSION(1:3,1:NumPtsDiskAvg)  :: DiskWindPosAbs = 0.0_ReKi      !< Position points for disk average sampling, absolute/global/interial [-]
    REAL(ReKi) , DIMENSION(1:3,1:NumPtsDiskAvg)  :: DiskWindVel = 0.0_ReKi      !< Velocity at disk average sampling points [-]
    REAL(ReKi) , DIMENSION(1:3)  :: DiskAvgVel = 0.0_ReKi      !< Average velocity calculated from DiskWindVel [-]
  END TYPE DiskAvgVelData
! =======================
CONTAINS

subroutine ADI_cbind_CopyDiskAvgVelData(SrcDiskAvgVelDataData, DstDiskAvgVelDataData, CtrlCode, ErrStat, ErrMsg)
   type(DiskAvgVelData), intent(in) :: SrcDiskAvgVelDataData
   type(DiskAvgVelData), intent(inout) :: DstDiskAvgVelDataData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ADI_cbind_CopyDiskAvgVelData'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstDiskAvgVelDataData%DiskWindPosRel = SrcDiskAvgVelDataData%DiskWindPosRel
   DstDiskAvgVelDataData%DiskWindPosAbs = SrcDiskAvgVelDataData%DiskWindPosAbs
   DstDiskAvgVelDataData%DiskWindVel = SrcDiskAvgVelDataData%DiskWindVel
   DstDiskAvgVelDataData%DiskAvgVel = SrcDiskAvgVelDataData%DiskAvgVel
end subroutine

subroutine ADI_cbind_DestroyDiskAvgVelData(DiskAvgVelDataData, ErrStat, ErrMsg)
   type(DiskAvgVelData), intent(inout) :: DiskAvgVelDataData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ADI_cbind_DestroyDiskAvgVelData'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ADI_cbind_PackDiskAvgVelData(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(DiskAvgVelData), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ADI_cbind_PackDiskAvgVelData'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%DiskWindPosRel)
   call RegPack(RF, InData%DiskWindPosAbs)
   call RegPack(RF, InData%DiskWindVel)
   call RegPack(RF, InData%DiskAvgVel)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ADI_cbind_UnPackDiskAvgVelData(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(DiskAvgVelData), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ADI_cbind_UnPackDiskAvgVelData'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%DiskWindPosRel); if (RegCheckErr(RF, RoutineName)) return
   call RegUnpack(RF, OutData%DiskWindPosAbs); if (RegCheckErr(RF, RoutineName)) return
   call RegUnpack(RF, OutData%DiskWindVel); if (RegCheckErr(RF, RoutineName)) return
   call RegUnpack(RF, OutData%DiskAvgVel); if (RegCheckErr(RF, RoutineName)) return
end subroutine
END MODULE AeroDyn_Inflow_C_Binding_Types
!ENDOFREGISTRYGENERATEDFILE
