[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "openfast_io"
# dynamic = ["version"]
version = "4.1.2"
description = "Readers and writers for OpenFAST files."
license = {file = "../LICENSE"}
authors = [
    {name = "Mayank Chetan", email = "mayank.chetan@nrel.gov"      },
    {name = "Andy Platt", email = "andy.platt@nrel.gov"            },
    {name = "Derek Slaughter", email = "derek.slaughter@nrel.gov"  },
    { name = "NREL WISDEM Team", email = "systems.engineering@nrel.gov"    },
]
maintainers = [
    {name = "Mayank Chetan", email = "mayank.chetan@nrel.gov"      },
    {name = "Andy Platt", email = "andy.platt@nrel.gov"            },
    {name = "Derek Slaughter", email = "derek.slaughter@nrel.gov"  },
]  
readme = "README.md"
requires-python = ">3.10"

classifiers = [  # Optional
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  # Indicate who your project is intended for
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",

  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",

  # Specify the Python versions you support here. In particular, ensure
  # that you indicate you support Python 3. These classifiers are *not*
  # checked by "pip install". See instead "python_requires" below.
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python",
]

dependencies = [
    "numpy",
    "pandas",
    "ruamel_yaml",
    "deepdiff",
    ]
    
[project.urls]
homepage = "https://github.com/OpenFAST/openfast"
documentation = "https://openfast.readthedocs.io/en/main/"
repository = "https://github.com/OpenFAST/openfast"
Issues = "https://github.com/OpenFAST/openfast/issues"



[project.optional-dependencies]

rosco = ["rosco"]
xlrd = ["xlrd"]
all = ["rosco", "xlrd"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "openfast_io/_version.py"
